# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
    wazuh.indexer:
        build:
            context: wazuh-indexer/
            args:
                WAZUH_VERSION: ${WAZUH_VERSION}
                WAZUH_TAG_REVISION: ${WAZUH_TAG_REVISION}
        image: gravityfargo/wazuh-indexer:${WAZUH_IMAGE_VERSION}
        hostname: wazuh.indexer
        restart: always
        ports:
            - "9200:9200"
        environment:
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
