# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
    generator:
        image: gravityfargo/wazuh-unraid-setup:4.8.0
        hostname: wazuh-unraid-setup
        container_name: wazuh-unraid-setup
        environment:
            - MANAGER_NAME=wazuh-manager
            - MANAGER_IP=10.10.10.101
            - INDEXER_NAME=wazuh-indexer
            - INDEXER_IP=10.10.10.100
            - INDEXER_USERNAME=admin
            - INDEXER_PASSWORD=SecretPassword
            - DASHBOARD_NAME=wazuh-dashboard
            - DASHBOARD_IP=10.10.10.102
            - UNRAID_USER=root
            - UNRAID_IP=10.10.10.10
            - FILEBEAT_SSL_VERIFICATION_MODE=full
            - API_USERNAME=wazuh-wui
            - API_PASSWORD=MyS3cr37P450r.*-
        volumes:
            - /mnt/user/appdata/wazuh-manager:/wazuh-manager
            - /mnt/user/appdata/wazuh-indexer:/wazuh-indexer
            - /mnt/user/appdata/wazuh-dashboard:/wazuh-dashboard
